# Introduction to Quantum Mechanics and Linear Algebra
    
In quantum mechanics, states and observables are represented using the mathematics of Hilbert spaces. 
However, their infinite dimensions is incompatible with numerical simulations, that always requires finite elements. 
Hence, we truncate Hilbert spaces to a finite size, allowing us to run the quantum calculation on a computer.
We can thus say that the whole problem of numerical quantum mechanics is then reduced to a problem of multilinear algebra, which is a generalization of linear algebra in tensor products of vector spaces.

The art of numerical quantum optics stands almost entirely in finding algorthms that allows us to arrive to the aimed result with the smallest possible truncated Hilbert space.
However, beside having efficient algorithms, the intricated tensor structures of many-body Hilbert spaces requires also a powerful organization of the code and an easy way to access relevant information.

## Quantum States and Operators for Dimension $N$=7

In a Hilbert space of dimension $N$=7, quantum states can still be represented as vectors, and operators as matrices. Here we demonstrate the destroy operator, $a$, which lowers the state by one quantum number.

The matrix representation of the destroy operator in a 7-dimensional Hilbert space is:

$$
\hat{a} = \begin{pmatrix}
0 & \sqrt{1} & 0 & 0 & 0 & 0 & 0 \\
0 & 0 & \sqrt{2} & 0 & 0 & 0 & 0 \\
0 & 0 & 0 & \sqrt{3} & 0 & 0 & 0 \\
0 & 0 & 0 & 0 & \sqrt{4} & 0 & 0 \\
0 & 0 & 0 & 0 & 0 & \sqrt{5} & 0 \\
0 & 0 & 0 & 0 & 0 & 0 & \sqrt{6} \\
0 & 0 & 0 & 0 & 0 & 0 & 0
\end{pmatrix}
$$

This operator acts on Fock states to lower their quantum number by one, with a factor of $\sqrt{n}$, where $n$ is the quantum number of the initial state.


In [3]:
import numpy as np

N = 7

def destroy(N):
    a = np.zeros((N, N))
    for i in range(N-1):
        a[i, i+1] = np.sqrt(i+1)
    return a

# Define the fock states
def fock(N, i):
    res = np.zeros(N)
    res[i] = 1
    return res

zero_state = fock(N, 0)
one_state = fock(N, 1)
two_state = fock(N, 2)
three_state = fock(N, 3)

destroy_operator = destroy(N)
destroy_operator

array([[0.        , 1.        , 0.        , 0.        , 0.        ,
        0.        , 0.        ],
       [0.        , 0.        , 1.41421356, 0.        , 0.        ,
        0.        , 0.        ],
       [0.        , 0.        , 0.        , 1.73205081, 0.        ,
        0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 2.        ,
        0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        2.23606798, 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 2.44948974],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        ]])

## Action of the Destroy Operator on a Fock State

The action of the destroy operator $a$ on a Fock state $|n\rangle$ lowers the state by one quantum number, multiplied by a factor $\sqrt{n}$. For example, applying $a$ to the state $|3\rangle$ yields:

$$ \hat{a}|3\rangle = \sqrt{3}|2\rangle $$

This demonstrates the lowering action of the destroy operator with a specific factor, dependent on the quantum number of the state being acted upon.


In [4]:
# Apply the destroy operator on the one state
result_state = np.dot(destroy_operator, three_state)

print("Resulting State:")
result_state

Resulting State:


array([0.        , 0.        , 1.73205081, 0.        , 0.        ,
       0.        , 0.        ])

### <span style="color:red">**Exercise!**</span>

<ins>*Write a function `expect(O, psi)` that calculates the expectation value of an operator $\hat{O}$ with a given state $\psi$. Then calculate $\langle 2 \vert \hat{a} \vert 2 \rangle$ and $\langle 2 \vert \hat{a}^\dagger \hat{a} \vert 2 \rangle$.*</ins>

In [ ]:
# Write your code here...


In [9]:
# Solution
def expect(O, psi):
    return np.dot(np.conj(psi), np.dot(O, psi))

print("Expectation Value 1:", expect(destroy_operator, fock(N, 2)))
print("Expectation Value 2:", expect(destroy_operator.T.conj().dot(destroy_operator), fock(N, 2)))

Expectation Value 1: 0.0
Expectation Value 2: 2.0000000000000004


## Tensor Products in Matrix Form

The tensor product of two matrices expands the dimensionality of the space, allowing us to describe composite systems. For two 3x3 matrices, A and B, their tensor product results in a 9x9 matrix. The calculation is as follows, given:

$$
A = \begin{pmatrix}
a_{11} & a_{12} & a_{13} \\
a_{21} & a_{22} & a_{23} \\
a_{31} & a_{32} & a_{33}
\end{pmatrix},\,
B = \begin{pmatrix}
b_{11} & b_{12} & b_{13} \\
b_{21} & b_{22} & b_{23} \\
b_{31} & b_{32} & b_{33}
\end{pmatrix},\,
A \otimes B = \begin{pmatrix}
a_{11}B & a_{12}B & a_{13}B \\
a_{21}B & a_{22}B & a_{23}B \\
a_{31}B & a_{32}B & a_{33}B
\end{pmatrix}
$$

The tensor product, $A \otimes B$, results in a 9x9 matrix. This process combines each element of A with the entire matrix B, expanding the representation of the composite system.


In [5]:
# Define two 3x3 matrices
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])

# Perform tensor product
tensor_product = np.kron(A, B)

print("Tensor Product of A and B:\n")
tensor_product

Tensor Product of A and B:



array([[ 9,  8,  7, 18, 16, 14, 27, 24, 21],
       [ 6,  5,  4, 12, 10,  8, 18, 15, 12],
       [ 3,  2,  1,  6,  4,  2,  9,  6,  3],
       [36, 32, 28, 45, 40, 35, 54, 48, 42],
       [24, 20, 16, 30, 25, 20, 36, 30, 24],
       [12,  8,  4, 15, 10,  5, 18, 12,  6],
       [63, 56, 49, 72, 64, 56, 81, 72, 63],
       [42, 35, 28, 48, 40, 32, 54, 45, 36],
       [21, 14,  7, 24, 16,  8, 27, 18,  9]])

## Partial Trace

The **partial trace** over a subsystem, say $B$, of a composite system $AB$, mathematically expresses as "tracing out" $B$, leaving the reduced state of $A$. For a bipartite state $\rho_{AB}$, the partial trace over $B$ is:

$$
\text{Tr}_B(\hat{\rho}_{AB}) = \sum_{i \in \mathcal{H}_B} \langle i| \hat{\rho}_{AB} |i\rangle
$$

where $\{|i\rangle\}$ forms a complete basis for subsystem $B$.

Let's try it with an entangled Bell's state between two qubits:

$$
\vert \phi^+ \rangle = \frac{1}{\sqrt{2}} \left( \vert 0, 0 \rangle + \vert 1, 1 \rangle \right)
$$

In [6]:
def ptrace(psi, subspace_to_keep, dim_subspace):
    dim1, dim2 = dim_subspace

    rho = np.outer(psi, psi.conj())

    # Reshape rho to separate the subsystems' degrees of freedom
    rho_reshaped = rho.reshape(dim1, dim2, dim1, dim2)

    if subspace_to_keep == 1:
        # Perform the trace over the second subsystem
        traced_out = np.trace(rho_reshaped, axis1=1, axis2=3)
    elif subspace_to_keep == 2:
        # Perform the trace over the first subsystem
        traced_out = np.trace(rho_reshaped, axis1=0, axis2=2)
    else:
        raise ValueError("subspace_to_keep must be either 1 or 2.")

    return traced_out

# Bell state between two qubits
phi_plus = ( np.kron(fock(2, 1), fock(2, 1)) + np.kron(fock(2, 0), fock(2, 0)) ) / np.sqrt(2)

# Reduced density matrix of the first qubit
rho_1 = ptrace(phi_plus, 1, (2, 2))
rho_1

array([[0.5, 0. ],
       [0. , 0.5]])

## Why QuTiP?

While NumPy and SciPy are powerful tools for numerical computations, they lack specific functionalities for efficiently handling complex quantum systems. QuTiP is designed to fill this gap, offering features such as:
- Easy manipulation and visualization of quantum objects.
- Support for operations on states and operators in different Hilbert spaces.
- Tools for dealing with composite systems, partial traces, and superoperators.
It is like to have the book "Quantum noise" (by Gardiner and Zoller) already implemented in your laptop!


In the next chapter, we'll explore how QuTiP simplifies these tasks, making it an invaluable tool for quantum optics simulations.
    